Areas/DocumentAdmin/Controllers/DocumentFormatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using QML.Library;
using QML.Library.Utilities;
using QML.Library.Helpers;
using QML.Library.Auth;
using QML.Library.Base.Controllers;
using QML.Library.Attributes;
using QML.Web.UI.Areas.DocumentAdmin.Helpers;
using QML.Web.UI.Areas.DocumentAdmin.Models;
using System.IO;
using System.Web.Helpers;

namespace QML.Web.UI.Areas.DocumentAdmin.Controllers
{
    public class DocumentFormatController : SecuredController
    {
        //
        // GET: /DocumentAdmin/DocumentFormat/
        HanuELibraryEntities db = new HanuELibraryEntities();
        [Menu(Title = "Danh sách", Path = "Định dạng văn bản", Order = 1)]
        public ActionResult Index()
        {
            var format = from f in db.DocumentFormats select f;
            return View(format.ToList());
        }

        //
        // GET: /DocumentAdmin/DocumentFormat/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /DocumentAdmin/DocumentFormat/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /DocumentAdmin/DocumentFormat/Create

        [HttpPost]
        public ActionResult Create(DocumentFormatModel model, HttpPostedFileBase file)
        {
            try
            {
                if ((file != null) && (file.ContentLength > 0))
                {
                    DocumentFormat entity = new DocumentFormat();
                    entity.Name = model.Name;
                    entity.Description = model.Description;
                    entity.MIME = model.MIME;
                    entity.FileFormat = model.FileFormat;

                    string fileName = Path.GetFileName(file.FileName);
                    string extension = "";
                    if (!string.IsNullOrEmpty(fileName))
                    {
                        fileName = fileName.Replace(" ", "_");
                        extension = fileName.Split('.')[(fileName.Split('.').Length - 1)].ToLower();
                    }

                    entity.Avatar = fileName;
                    entity.Status = model.Status;
                    var path = Path.Combine(HttpContext.Server.MapPath("~/uploads"), fileName);
                    file.SaveAs(path);
                    FileInfo finfo = new FileInfo(HttpContext.Server.MapPath("~/uploads/" + fileName));
                    long FileInBytes = finfo.Length;
                    long FileInKB = finfo.Length / 1024;


                    db.DocumentFormats.AddObject(entity);
                    db.SaveChanges();

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return RedirectToAction("Index");
        }
        
        //
        // GET: /DocumentAdmin/DocumentFormat/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /DocumentAdmin/DocumentFormat/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /DocumentAdmin/DocumentFormat/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /DocumentAdmin/DocumentFormat/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                DocumentFormat entity = db.DocumentFormats.FirstOrDefault(p => p.DocumentFormatID == id);
                db.DocumentFormats.DeleteObject(entity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Areas/DocumentAdmin/Views/DocumentFormat/Create.cshtml
@model QML.Web.UI.Areas.DocumentAdmin.Models.DocumentFormatModel

@{
    ViewBag.Title = "QUẢN LÝ ĐỊNH DẠNG TÀI LIỆU";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
						
<fieldset class="form">
    <legend>Thêm mới danh mục</legend>				
	@using (Html.BeginForm("Create", "DocumentFormat", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
            @Html.ValidationSummary(true)     
            <label>
            @Html.Localize("Tên định dạng")
            </label>
            @Html.EditorFor(model => model.Name)
			
			<label>
            @Html.Localize("Mô tả")
            </label>
            @Html.EditorFor(model => model.Description)

			<label>
            @Html.Localize("MIME")
            </label>
            @Html.EditorFor(model => model.MIME)

			<label>
            @Html.Localize("Đuôi định dạng")
            </label>
            @Html.EditorFor(model => model.FileFormat)

			<label>
            @Html.Localize("Icon(*)")
            </label>
            <input type="file" name="file" />

            <label>
            @Html.Localize("Trạng thái")	
            </label>
            @*Html.DropDownListFor(model => model.Status, new SelectList(new List<Object>{new {value = "True", text="True"},new {value = "False", text="False"}}, new { @Class = "styled" })*@
            @Html.DropDownListFor(model => model.Status, new SelectList(
                  new List<Object>{ 
                       new { value = "True" , text = "True"  },
                       new { value = "False" , text = "False" },                       
                    },
                  "value",
                  "text",
                   2))
            <div class="action">
                <button class="button button-green">@Html.Localize("Thêm mới")</button>
                @Html.ActionLinkButtonSecured(Html.Localize("Hủy bỏ"), null, "Index", "DocumentFormat", "Document")
            </div>
            <span>Tuong (*) bat buoc</span>
    }

</fieldset>

Areas/DocumentAdmin/Views/DocumentFormat/Delete.cshtml
@model QML.Web.UI.Areas.DocumentAdmin.Models.DocumentFormatModel

@{
    ViewBag.Title = "QUẢN LÝ DANH MỤC TÀI LIỆU";
}

<fieldset>
    <legend>Xóa bỏ định dạng tài liệu</legend>
<h3>Bạn có chắc chắn muốn xóa định đạng tài liệu này?</h3>
@using (Html.BeginForm()) {
    <p>
        <button class="button button-red">@Html.Localize("Xóa")</button>
        @Html.ActionLink("Trở về danh sách", "Index")
    </p>
}
</fieldset>

Areas/DocumentAdmin/Views/DocumentFormat/Index.cshtml
@model IEnumerable<QML.Web.UI.DocumentFormat>

@{
    ViewBag.Title = "QUẢN LÝ ĐỊNH DẠNG TÀI LIỆU";
}

<h2>Danh sách</h2>
<!--
<p>
    @Html.ActionLink("Thêm mới", "Create", "DocumentFormat", null, new { @class = "link-button-green" })
</p>
-->
<ul id="browser" class="filetree">
 @MvcHtmlString.Create(ViewBag.tree_cate)
</ul>


@{
    var grid = new WebGrid(
        source: Model.ToList(),
        rowsPerPage: 10
        );
}
@grid.GetHtml(
    tableStyle: "datatable",                
    columns: grid.Columns(
        grid.Column(columnName: "Name", header: "Tên định dạng"),
        grid.Column(columnName: "Description", header: "Mô tả"),
        grid.Column(columnName: "MIME", header: "MIME"),
        grid.Column(columnName: "FileFormat", header: "Đuôi định dạng"),
        grid.Column(header: "Icon", format: @<text><img src="@Url.Content("~/uploads/" + @item.Avatar)" style="width:64px; height:64px" alt="" /></text>)
        //grid.Column(header: "Hành động", format: 
        //@<text>@Html.ActionLink("Xóa", "Delete", new { id = item.DocumentFormatID })</text>)
    ),
    htmlAttributes: new { cellpadding = "0", cellspacing = "0", width = "100%" },
    footerStyle: "pagination"
)