Backup/Areas/DocumentAdmin/Controllers/TopDocumentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QML.Library;
using QML.Library.Utilities;
using QML.Library.Helpers;
using QML.Library.Auth;
using QML.Library.Base.Controllers;
using QML.Library.Attributes;
using QML.Web.UI.Areas.DocumentAdmin.Helpers;
using QML.Web.UI.Areas.DocumentAdmin.Models;
using System.IO;
using System.Web.Helpers;

namespace QML.Web.UI.Areas.DocumentAdmin.Controllers
{ 
    public class TopDocumentController : SecuredController
    {
        private HanuELibraryEntities db = new HanuELibraryEntities();

        //
        // GET: /DocumentAdmin/TopDocument/
        [Menu(Title = "Tài liệu được đọc nhiều nhất", Path = "Thống kê", Order = 3)]
        public ViewResult Index(FormCollection c)
        {
            IEnumerable<DocumentEssential> model = (from df in db.DocumentsFiles
                                                    join doc in db.Documents on df.DocumentID equals doc.DocumentID
                                                    select new DocumentEssential
                                                    {
                                                        DocumentID = df.DocumentID,
                                                        BookFee = df.BookFee.Value,
                                                        CategoryID = df.CategoryID.Value,
                                                        Description = doc.Description,
                                                        FormatID = df.FormatID.Value,
                                                        IsDeleted = df.IsDeleted.Value,
                                                        Status = df.Status,
                                                        Subject = doc.Subject,
                                                        IsHasInfo = df.IsHasInfo.Value,
                                                        Language = doc.Language,
                                                        Thumbnail = df.Thumbnail,
                                                        Title = doc.Title,
                                                        ViewCount = df.ViewCount.Value,
                                                        Creator = doc.Creator,
                                                        Identifier = doc.Identifier,
                                                        Publisher = doc.Publisher,
                                                        Format = doc.Format,
                                                        FileSource = df.FileSource,
                                                        Contributor = doc.Contributor,
                                                        Coverage = doc.Coverage,
                                                        Relation = doc.Relation,
                                                        Resource = doc.Resource,
                                                        Right = doc.Right,
                                                        Type = doc.Type,
                                                        CategoryName = db.DocumentCategories.FirstOrDefault(p => p.CategoryID == df.CategoryID).CategoryName,
                                                    });
            if (c.GetValue("top") == null)
                return View(model.OrderByDescending(p => p.ViewCount).Take(10).ToList());
            else
            {
                int top = int.Parse(c.GetValue("top").AttemptedValue);
                return View(model.OrderByDescending(p => p.ViewCount).Take(top).ToList());
            } 
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Backup/Areas/DocumentAdmin/Views/TopDocument/Index.cshtml
@model IEnumerable<QML.Web.UI.Areas.DocumentAdmin.Models.DocumentEssential>

@{
    ViewBag.Title = "Tài liệu được đọc nhiều nhất";
    var id = 0;
}
@helper TruncateString(string input, int length)
{
    if(input != null)
    {
        if (input.Length <= length) {
            @input
        } else {
            @input.Substring(0, length)<text>...</text>
        }
    }
}
<h2>Tài liệu được đọc nhiều nhất</h2>

@using (Html.BeginForm("Index", "TopDocument", FormMethod.Post)){
    <select name="top">
        <option value="10" selected="selected">Danh sách 10</option>
        <option value="20">Danh sách 20</option>
        <option value="50">Danh sách 30</option>
    </select>
    <input type="submit" name="submit" value="Hiển thị" />
}
<hr />
@{

                var grid = new WebGrid(
                    source: Model.ToList(), 
                    rowsPerPage: 30
                    );

}
@grid.GetHtml(
    tableStyle: "datatable",                
    columns: grid.Columns(
        grid.Column(header: "Hình đại diện", format: @<text><img src="@Url.Content("~/uploads/" + @item.Thumbnail)" width="80px" height="100px" alt=""/></text>),
        grid.Column(header: "Tiêu đề", format: @<text>@TruncateString(item.Title, 20)</text>),
        grid.Column(header: "Tác giả", format: @<text>@item.Creator</text>),
        grid.Column(header: "Danh mục", format: @<text>@item.CategoryName</text>),
        grid.Column(header: "Nhà xuất bản", format: @<text>@item.Publisher</text>),
        grid.Column(header: "Ngôn ngữ", format: @<text>@item.Language</text>), 
        grid.Column(header: "Lượng truy cập", format: @<text>@item.ViewCount</text>),
        grid.Column(header: "Giá", format: @<text>@String.Format("{0:0,0.0}", item.BookFee)</text>)
    ),
        htmlAttributes: new { cellpadding = "0", cellspacing = "0", width = "100%" },
        footerStyle: "pagination"
)